name: MSBuild

on: workflow_dispatch

jobs:
  build:
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v3

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Restore NuGet packages
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: nuget restore .

    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild . /p:Platform=x86 /p:OutputPath=x86 && msbuild . /p:Platform=ARM /p:OutputPath=ARM

    - name: Upload
      uses: actions/upload-artifact@v3
      with:
         name: MSBuild
         path: .
